# Vagrant configuration.

box_name: bento/ubuntu-20.04
box_version: 202112.19.0

domain: cluster.local

infra_network:
  prefix: 24
  network: 10.196.56.0

deployer_certificate_directory: /etc/kubernetes/pki
deployer_configuration_directory: /opt/deployer/config

vrrp_nic: eth1

kubernetes_vip: 10.196.56.10
kubernetes_vip_port: 8443
kubernetes_api_port: 6443

kubernetes_release: v1.23.0
cfssl_version: "1.6.1"
cri_containerd_cni_release: 1.6.6

cluster_cidr: 10.200.0.0/16

infra_provider: virtualbox

servers:
  - id: kube-master-1
    enable: true
    box: bento/ubuntu-20.04
    box_version: 202112.19.0
    base_mac: 00:0c:29:31:ff:3b
    base_address: 10.196.56.11
    hostmanager:
      manage_guest: true
    ansible_user: vagrant
    resources:
      memory: 2048
      cpus: 4
    roles:
      - etcd
      - kube_master
      - load_balancer

  - id: kube-master-2
    enable: true
    box: bento/ubuntu-20.04
    box_version: 202112.19.0
    base_mac: 00:0c:29:31:ff:3c
    base_address: 10.196.56.12
    hostmanager:
      manage_guest: true
    ansible_user: vagrant
    resources:
      memory: 2048
      cpus: 4
    roles:
      - etcd
      - kube_master
      - load_balancer

  - id: kube-master-3
    enable: true
    box: bento/ubuntu-20.04
    box_version: 202112.19.0
    base_mac: 00:0c:29:31:ff:3d
    base_address: 10.196.56.13
    hostmanager:
      manage_guest: true
    ansible_user: vagrant
    resources:
      memory: 2048
      cpus: 4
    roles:
      - etcd
      - kube_master
      - load_balancer

  - id: kube-worker-1
    enable: true
    box: bento/ubuntu-20.04
    box_version: 202112.19.0
    base_mac: 00:0c:29:31:ff:3e
    base_address: 10.196.56.14
    hostmanager:
      manage_guest: true
    ansible_user: vagrant
    resources:
      memory: 1024
      cpus: 4
    roles:
      - kube_worker
    pod_cidr: 10.200.0.0/24

  - id: kube-worker-2
    enable: true
    box: bento/ubuntu-20.04
    box_version: 202112.19.0
    base_mac: 00:0c:29:31:ff:3f
    base_address: 10.196.56.15
    hostmanager:
      manage_guest: true
    ansible_user: vagrant
    resources:
      memory: 1024
      cpus: 4
    roles:
      - kube_worker
    pod_cidr: 10.200.1.0/24

  - id: kube-worker-3
    enable: true
    box: bento/ubuntu-20.04
    box_version: 202112.19.0
    base_mac: 00:0c:29:31:ff:3g
    base_address: 10.196.56.16
    hostmanager:
      manage_guest: true
    ansible_user: vagrant
    resources:
      memory: 1024
      cpus: 4
    roles:
      - kube_worker
    pod_cidr: 10.200.2.0/24

  - id: infra-deployer
    enable: true
    box: bento/ubuntu-20.04
    box_version: 202112.19.0
    base_mac: 00:0c:29:31:ff:3a
    base_address: 10.196.56.5
    hostmanager:
      manage_guest: true
    ansible_user: vagrant
    resources:
      memory: 1024
      cpus: 4
    roles:
      - deployer
      - kube_worker
