- name: "Get Containerd"
  ansible.builtin.unarchive:
    src: "https://github.com/containerd/containerd/releases/download/v{{ containerd_release_version }}/cri-containerd-{{ containerd_release_version }}-linux-amd64.tar.gz"
    dest: "/"
    remote_src: yes

#- name: "remove a 10-containerd-net.conflist cni config files"
#  file: path=/etc/cni/net.d/10-containerd-net.conflist state=absent

- name: "Create a directory for cni binary"
  file: path={{ cni_bin_dir }} state=directory

- name: "Create a directory for cni config files"
  file: path={{ cni_conf_dir }} state=directory

- name: "Create a directory for containerd config"
  file: path=/etc/containerd state=directory

- name: "Start Containerd"
  systemd: name=containerd daemon_reload=yes state=restarted enabled=yes
#- name: Prepare configuration for Forwarding IPv4 and letting iptables see bridged traffic
#  ansible.builtin.copy:
#    src: "/vagrant/ansible/files/crictl.yaml"
#    dest: "/etc/crictl.yaml"
