- name: Download the Google Cloud public signing key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Add the Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes

- name: "Update the repository cache (Ubuntu)"
  apt:
    update_cache: yes

- name: "Install kubelet, kubeadm packages (Ubuntu)"
  ansible.builtin.apt:
    pkg:
      - kubelet=1.23.9-00
      - kubeadm=1.23.9-00
    allow_downgrade: true
    autoclean: true
    autoremove: true

- name: "Install kubectl packages (Ubuntu)"
  ansible.builtin.apt:
    pkg:
      - kubectl=1.23.9-00
      - kubetail
    allow_downgrade: true
    autoclean: true
    autoremove: true
  when: inventory_hostname == groups['kube_master'][0]

- name: Prevent kubernetes from being upgraded
  ansible.builtin.dpkg_selections:
    name: "{{item}}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - kubetail

- name: Enable kubectl autocompletion
  ansible.builtin.shell: kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/null
  when: inventory_hostname == groups['kube_master'][0]

- name: "Check kubelet args in kubelet config (Ubuntu)"
  shell: grep "^Environment=\"KUBELET_EXTRA_ARGS=" /etc/systemd/system/kubelet.service.d/10-kubeadm.conf || true
  register: check_args

- name: "Add runtime args in kubelet conf (Ubuntu)"
  lineinfile:
    dest: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
    line: 'Environment="KUBELET_EXTRA_ARGS= --runtime-cgroups=/system.slice/containerd.service --container-runtime=remote --runtime-request-timeout=15m --container-runtime-endpoint=unix:///run/containerd/containerd.sock"'
    insertafter: '\[Service\]'

- name: "Start Kubelet"
  systemd: name=kubelet daemon_reload=yes state=started enabled=yes

- name: "Pre-pull pause container image"
  shell: |
    /usr/local/bin/ctr image pull k8s.gcr.io/pause:3.7

- name: Add the HashiCorp GPG key.
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /usr/share/keyrings/hashicorp-release-keyring.gpg
  when: inventory_hostname == groups['kube_master'][0]

- name: Add the HashiCorp apt repository.
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-release-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    filename: hashicorp
  when: inventory_hostname == groups['kube_master'][0]

- name: "Update the repository cache (Ubuntu) for HashiCorp Packages"
  apt:
    update_cache: yes
  when: inventory_hostname == groups['kube_master'][0]

- name: "Install consul-k8s (Ubuntu)"
  ansible.builtin.apt:
    pkg:
      - consul-k8s
    allow_downgrade: true
    autoclean: true
    autoremove: true
  when: inventory_hostname == groups['kube_master'][0]
